name: Publish

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: integration-template_1.0.3.zip
            asset_name: integration-template_1.0.3.zip
    steps:
      - name: Download Release Asset
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "fiddlermikey/githubscripting"
#          token: ${{ github.token }}
          latest: true
          fileName: "*.zip"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: 1.0.0
          overwrite: true

