name: Publish

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: integration-template_1.0.3.zip
            asset_name: integration-template_1.0.3.zip
    steps:
      - name: Download Release Asset
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "fiddlermikey/githubtesting"
          token: ${{ github.token }}
          latest: true
          fileName: "*.zip"
          github-api-url: "https://keyfactor.com/api/v3"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

