name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Setup build environment
        id: setup_env
        run: |
            $repoName = "${{ github.repository }}".Split("/")
            echo "Repo Name: $($repoName[-1])"
            echo "REPO_NAME=$($repoName[-1])" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append

            $releaseURL = "${{ github.repository }}".getLatestRelease($(repoName),"fiddlermikey")
            echo "$releaseURL: $(releaseURL)"
            echo "releaseURL=$(releaseURL)" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Read Variable
        id: read_var
        run: echo "releaseURL=$Env:releaseURL"