name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Download Release Asset
        id: downloadAsset
        uses: robinraju/release-downloader@main
        with:
          repository: ${{ github.repository }}  
          token: ${{ github.token }}
          latest: true
          fileName: "*.zip"
          github-api-url: "https://keyfactor.com/api/v3"
        
      - name: debug output
        run: |
          echo "latestReleaseTag = ${{ steps.downloadAsset.outputs.tag_name }}"
          