name: Build Docker Images
on: [push, repository_dispatch]

jobs:
  build:
    name: RedisTimeSeries
    runs-on: windows-latest
    steps:
      - id: find-latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fiddlermikey
          repo: githubscripting
          excludes: prerelease, draft
      - id: display-latest
        run: |
          Write-Output "Latest release tag is ${{ steps.find-latest.outputs.release }}"
          Write-Output "Latest release id is ${{ steps.find-latest.outputs.id }}"
