name: Replace Files Test
on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read Branch
        id: read-branch
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const repoName = context.repo.repo;
            const branchName = context.ref.split('/');
            const tBranchName = branchName[branchName.length -1];
            const nBranchName = context.ref.split('/')[context.ref.split('/').length-1]
            console.log(`Repo name: ${repoName}`);
            console.log(`Target branch name: ${branchName}`);
            console.log(`Truncated branch name: ${tBranchName}`);
            console.log(`nBranchName: ${nBranchName}`);
      - name: Exec PS Command
        id: exec-ps
        run: |
          Get-Content .\.github\workflows\main.yml
          Copy-Item newmain.yml .\.github\workflows\main.yml -Force
          Get-Content .\.github\workflows\main.yml
          
          