name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Setup build environment
        id: setup_env
        uses: actions/github-script@v4.0.2
        with:
          script: |
            console.log('Begin Script')
            const repoName = github.repository.split('/')[1]
            console.log('End Script')