name: HELLO_WORLD Testing
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: fiddlermikey/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mikey the Great'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"      
      - name: Read Branch
        id: read-branch
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const pulls = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const state = (pulls.data[0].state != '') ? pulls.data[0].state : 'empty';
            const repoName = context.repo.repo;
            const targetBranchName = pulls.data[0].base.ref;
            console.log(`Repo name: ${repoName}`);
            console.log(`Repo state: ${state}`);
            console.log(`Target branch name: ${targetBranchName}`);
            const IS_RELEASE = (targetBranchName.startsWith('release-'));
            console.log(`${IS_RELEASE}`);
