name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Setup build environment
        id: setup_env
        uses: actions/github-script@v4.0.2
        with:
          script: |
            console.log('Begin Script')
            const repoName = context.repo.repo
            const repoOwner = context.repo.owner
            const uploadURL = context.repo.getLatestRelease({
              owner: repoOwner
              repo: repoName
            })
            console.log(repoOwner + '/' + repoName)
            core.exportVariable('repoName', repoName)
            core.exportVariable('repoOwner', repoOwner)
            core.exportVariable('uploadURL', uploadURL)
            console.log('End Script')

      - name: Read Variable
        id: read_var
        run: |
          echo "repoName=$Env:repoName"
          echo "repoOwner=$Env:repoOwner"
          echo "uploadURL=$Env:uploadURL"
            