name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token}}
          latest: true
          #owner: fiddlermikey
          #repo: githubscripting
          

      - name: Setup build environment
        id: setup_env
        uses: actions/github-script@v4.0.2
        with:
          script: |
            console.log('Begin Script')
            const repoName = context.repo.repo
            const repoOwner = context.repo.owner
            const latestRelease = context.repo.getLatestRelease
            console.log(repoOwner + '/' + repoName)
            const upldURL = ${{ steps.latest_release.output.upload_url}}
            core.exportVariable('repoName', repoName)
            core.exportVariable('repoOwner', repoOwner)
            core.exportVariable('latestRelease', latestRelease)
            console.log('End Script')

      - name: Read Variable
        id: read_var
        run: |
          echo "repoName=$Env:repoName"
          echo "repoOwner=$Env:repoOwner"
          echo "latestRelease=$Env:latestRelease"
          
#             // const latestRelease = context.repo.getLatestRelease
                      #core.exportVariable('uploadURL', uploadURL)
