name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on:  [self-hosted, kf-integ-test]
    steps:
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token}}
          latest: true
          #owner: fiddlermikey
          #repo: githubscripting
      - name: Echo Values
        run: |
          echo "ID: ${{ steps.latest_release.outputs.id}}"
          echo "Tag: ${{ steps.latest_release.outputs.tag_name}}"
          echo "upload_url: ${{ steps.latest_release.output.upload_url}}"