# This is a basic workflow to help you get started with Actions

name: SPUpload Testing
on: [workflow_dispatch, push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

      - name: Create a test file
        run: echo "test" > test.txt

      - name: SharePoint uploader
        uses: su-dont/share-point-uploader@v2.1
        with:
          sp_url: https://keyfactorinc.sharepoint.com/sites/CenterforProductReadiness
          sp_username: ${{ secrets.SPO_USERNAME }}
          sp_password: ${{ secrets.SPO_PASSWORD }}
          sp_folder: /Documents/CPR Staff Working/Mikey/upload
          sp_file_name: test.txt
          file: test.txt

